name:ci/cd pipeline
on:
push:
branches:[main]
workflow_dispathch:
jobs:
pipeline:
runs-on:ubuntu-latest
steps:
-uses:action/chechout@v4
-uses:action/checkout@v4
-with:{node-version:18}
-runs:npm install
-runs:echo"build"
-runs:npm test
-runs:echo"deploy"

